language: c
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get update -qq
script:
 - make
 - ./test-backtrace.sh
notifications:
  irc:
    channels:
      - "irc.freenode.org#gentoo-hardened"
    on_success: change
    on_failure: always
